---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.5
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.7.1
---

# Introduction to data frames

Start by loading the usual plotting libraries.

```{python}
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
# Make plots look a little bit more fancy
plt.style.use('fivethirtyeight')
```

[Pandas](https://pandas.pydata.org) is a Python package that
implements data frames, and functions that operate on data
frames.

```{python}
import pandas as pd
```


## Data frames and series

We start by loading data from a Comma Separated Value file (CSV
file).  If you are running on your laptop, you should download
the [gender_stats.csv]({{ site.baseurl }}/data/gender_stats.csv)
file to the same directory as this notebook.

```{python}
# Load the data file
gender_data = pd.read_csv('gender_stats.csv')
```

This is our usual assignment statement. The LHS is `gender_data`, the variable name.  The RHS is an expression, that returns a value.

What type of value does it return?

```{python}
type(gender_data)
```

Pandas integrates with the Notebook, so, if you display a data
frame in the notebook, it does a nice display of rows and
columns.

```{python}
gender_data
```

The data frame has rows and columns.  Like other Python objects, it has *attributes*.  These are pieces of data associated with the data frame.  You have already seen *methods*, which are functions associated with the data frame.  You can access attributes in the same way as you access methods, by typing the variable name, followed by a dot `.`, followed by the attribute name.

For example, one attribute of the data frame, is the `shape`:

```{python}
gender_data.shape
```

Another attribute is `columns`.  This has the column names. For
example, here is a good way of quickly seeing the column names
for a data frame:

```{python}
gender_data.columns
```

You need more information about what these column names refer to.  Here are the longer descriptions from the original data source (link above):

* `fert_rate`: Fertility rate, total (births per woman).
* `gdp`: GDP (current US\$).
* `health_exp_per_cap`: Health expenditure per capita, PPP (constant 2011 international \$).
* `health_exp_pub`: Health expenditure, public (% of GDP).
* `prim_ed_girls`: Primary education, pupils (% female).
* `mat_mort_ratio`: Maternal mortality ratio (modeled estimate, per 100,000 live births).
* `population`: Population, total.

You have just seen array slicing (in [Selecting with
arrays](../03/array_indexing).  You remember that array slicing
uses square brackets.   Data frames also allow slicing.  For
example, we often want to get all the data for a single column
of the data frame.  To do this, we use the same square bracket
notation as we use for array slicing, with the name of the
column inside the square brackets.

```{python}
gdp = gender_data['gdp']
```

What `type` of thing is this column of data?

```{python}
type(gdp)
```

Here are the values for `gdp`.  You will notice that these are
the same values you saw in the "gdp" column when you displayed
the whole data frame.

```{python}
gdp
```

What are these values like `6.405000e+08`?  These are numbers,
in [scientific
notation](https://en.wikipedia.org/wiki/Scientific_notation).
Scientific notation is a compact way of writing very large or
very small numbers.  The value after `e` above is the
*exponent*, in this case `08`.  The number above means $6.405
* $10^8$. For example, here is $2 * 10^7$:

```{python}
2e7
```


## Missing values and `NaN`

Looking at the values of `gdp` (and therefore, the values of the
`gdp` column of `gender_data`, we see that some of the values
are `NaN`, which means Not a Number.  Pandas uses this marker to
indicate values that are not available, or *missing data*.

Numpy does not like to calculate with `NaN` values.  Here is Numpy trying to calculate the median of the `gdp` values.

```{python}
np.median(gdp)
```

Notice the warning about an invalid value.

Numpy recognizes that one or more values are `NaN` and refuses to guess what to do, when calculating the median.

You saw from the shape above that `gender_data` has 263 rows.  We can use the general Python `len` function, to see how many elements there are in `gdp`.

```{python}
len(gdp)
```

As expected, it has the same number of elements as there are rows in `gender_data`.

The `count` method of the series gives the number of values that are not missing - that is - not `NaN`.

```{python}
gdp.count()
```


## Plotting with methods

The `gdp` variable is a sequence of values, so we can do a histogram on these values, as we have done histograms on arrays.

```{python}
plt.hist(gdp)
```

Notice the multiple warnings as Matplotlib tried to calculate the bin widths for the histogram.  These are from the `NaN` values.

Another way to do the histogram, is to use the `hist` method of the series.  Using the method can make the code a bit easier to read, and the method does discard the `NaN` values, by default, so it does not generate the same warnings.

```{python}
gdp.hist()
```

Now we have had a look at the GDP values, we will look at the
values for the `mat_mort_ratio` column.  These are the numbers
of women who die in childbirth for every 100,000 births.

```{python}
mmr = gender_data['mat_mort_ratio']
mmr
```

```{python}
mmr.hist()
```

We are interested in the relationship of `gpp` and `mmr`.  Maybe richer countries have better health care, and fewer maternal deaths.

Here is a plot, using the standard Matplotlib `scatter`
function.

```{python}
plt.scatter(gdp, mmr)
```

We can do the same plot using the `plot.scatter` method on the data frame.  In that case, we specify the column names that should go on the x and the y axes.

```{python}
gender_data.plot.scatter('gdp', 'mat_mort_ratio')
```

One advantage of doing it this way is that we get the column names on the x and y axes by default.

We often want to select rows from the data frame.

Say we want to select the rows corresponding the countries with a high GDP.

Looking at the histogram of `gdp` above, we could try this as a threshold to identify high GDP countries.

```{python}
high_gdp = gdp > 1e13
high_gdp
```

```{python}
type(high_gdp)
```

Notice that `high_gdp` is a Boolean series, like the Boolean arrays you have already seen.  It has `True` for elements corresponding to countries with `gdp` value greater than `1e13` and `False` otherwise.

We can use this Boolean series to select rows from the data frame.  The `loc` attribute of the data frame allows us to *locate* values in the data frame.  For our Boolean series, it works like this:

```{python}
rich_gender_data = gender_data.loc[high_gdp]
rich_gender_data
```

```{python}
type(rich_gender_data)
```

`rich_gender_data` is a new data frame, that is a subset of the
original `gender_data` frame.  It contains only the rows where
the GDP value is greater than `1e13` dollars.  Check the display
of `rich_gender_data` above to confirm that the values in the
`gdp` column are all greater than `1e13`.

We can do a scatter plot of GDP values against maternal
mortality rate, and we find, oddly, that for rich countries,
there is little relationship between GDP and maternal mortality.

```{python}
rich_gender_data.plot.scatter('gdp', 'mat_mort_ratio')
```
