---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.5
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.7.1
---

# Job Opportunities & Education in Rural India

A [study](http://www.nber.org/papers/w16021.pdf) at UCLA investigated
factors that might result in greater attention to the health and
education of girls in rural India. One such factor is information
about job opportunities for women. The idea is that if people know
that educated women can get good jobs, they might take more care of
the health and education of girls in their families, as an investment
in the girls’ future potential as earners.

The study focused on 160 villages outside the capital of India, all
with little access to information about call centers and similar
organizations that offer job opportunities to women. In 80 of the
villages chosen at random, recruiters visited the village, described
the opportunities, recruited women who had some English language
proficiency and experience with computers, and provided ongoing
support free of charge for three years. In the other 80 villages, no
recruiters visited and no other intervention was made.

At the end of the study period, the researchers recorded data about
the school attendance and health of the children in the villages.


**Question 1.** Which statement best describes the *treatment* and *control* groups for this study? Assign either 1, 2, or 3 to the name `jobs_q1` below.

1. The treatment group was the 80 villages visited by recruiters, and the control group was the other 80 villages with no intervention.

2. The treatment group was the 160 villages selected, and the control group was the rest of the villages outside the capital of India.

3. There is no clear notion of *treatment* and *control* group in this study.

```{python}
jobs_q1 = ...
```

**Question 2.** Was this an observational study or a randomized
controlled experiment? Assign either 1, 2, or 3 to the name `jobs_q2`
below.

1. This was an observational study.

2. This was a randomized controlled experiment.

3. This was a randomized observational study.

```{python}
jobs_q2 = ...
```

**Question 3.** The study reported, “Girls aged 5-15 in villages that
received the recruiting services were 3 to 5 percentage points more
likely to be in school and experienced an increase in Body Mass Index,
reflecting greater nutrition and/or medical care. However, there was
no net gain in height. For boys, there was no change in any of these
measures.” Why do you think the author points out the lack of change
in the boys?


*Write your answer here, replacing this text.*


## Nearsightedness Study

Myopia, or nearsightedness, results from a number of genetic and
environmental factors. In 1999, Quinn *et al* studied the relation
between myopia and ambient lighting at night (for example, from
nightlights or room lights) during childhood.

Quinn, G. E., Shin, C. H., Maguire, M. G., & Stone, R. A. (1999). Myopia and ambient lighting at night. Nature, 399(6732), 113.


**Question 1**. The data were gathered by the following procedure,
reported in the study. “Between January and June 1998, parents of
children aged 2-16 years ... that were seen as outpatients in
a university pediatric ophthalmology clinic completed a questionnaire
on the child’s light exposure both at present and before the age of
2 years.” Was this study observational, or was it a controlled
experiment?


*Write your answer here, replacing this text.*


**Question 2**

The study found that of the children who slept with a room light on
before the age of 2, 55% were myopic. Of the children who slept with
a night light on before the age of 2, 34% were myopic. Of the children
who slept in the dark before the age of 2, 10% were myopic. The study
concluded that, “The prevalence of myopia ... during childhood was
strongly associated with ambient light exposure during sleep at night
in the first two years after birth.” Do the data support this
statement? You may interpret “strongly” in any reasonable qualitative
way.


*Write your answer here, replacing this text.*


**Question 3**

On May 13, 1999, CNN reported the results of this study under the
headline, [Night light may lead to
nearsightedness](http://edition.cnn.com/HEALTH/9905/12/children.lights/index.html).
Does the conclusion of the study claim that night light causes
nearsightedness?


*Write your answer here, replacing this text.*


**Question 4**

The final paragraph of the CNN report said that “several eye
specialists” had pointed out that the study should have accounted for
heredity. Myopia is passed down from parents to children. In what way
do you think this fact might have affected the data?


*Write your answer here, replacing this text.*
