---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.6.5
---

# Assignment 4


## Breaking down expressions


The most important idea in Computer Science is that complicated, useful things
can be built by putting together simple parts according to simple rules. Python
code is an important example of this principle. Once you understand the basic
rules, you can code with confidence. These exercises are designed to give you
some practice with those rules.

First, a brief review of sub-expressions.

You can take any Python expression that has a value and combine it with other
expressions. For example, you can combine two number-valued expressions by
putting a + between them to add their values together. This forms a new, larger
expression called a compound expression. The expressions that were combined
together are called sub-expressions.

You can tell if something is a sub-expression by checking whether it would make
sense to write it in a line by itself. For example, in the expression 2 * 3, 2
is a sub-expression, but 2 * isn't, because 2 * isn't a valid expression. (Try
executing it!)


**Question 1.** List all the sub-expressions of the following expression:

`2 + 3`

Put each sub-expression on its own line in the next cell.

*Hint:* There are two of them.

```{python}
...
...
```

**Question 2.**  Expressions with variables.

Let us say that I have defined two variables, like this:

```{python}
a = 10
b = 5
```

Now list all the sub-expressions of the following expression:

`a + b`

Put each sub-expression on its own line in the next cell.

```{python}
...
...
```

**Question 3.**  List all the sub-expressions of the following expression:

`(a + 3) / b`

Here is a list of almost all the sub-expressions of that expression.  One is
missing.

1. `a`
2. `3`
3. `b`

In the next cell, write the missing expression.

```{python}
...
```

**Question 4.** Consider the following expression:

`(1 + 2) * ((3 / 4) ** 5)`

Here is a list of almost all the sub-expressions of that expression.  One is
missing.

1. `1`
2. `2`
3. `3`
4. `4`
5. `5`
6. `(1 + 2)`
7. `((3 / 4) ** 5)`

In the next cell, write the missing expression.

```{python}
...
```

**Question 5.** List all the sub-expressions of the following expression:

`(((2 ** 3) / 4) / 5) - 6`

Put each sub-expression on its own line in the next cell.

*Hint* - there are eight of them.

```{python}
...
...
...
...
...
...
...
...
```

**Question 6.**.  Where are the variables now?

Consider the following cell.  Execute it, to show the value of y.

```{python}
x = 10
y = x * 3
x = 100
y
```

Why is `y` equal to 30, and not 300?  Explain in the text cell below.
(Remember, double-click the cell to edit it, and then press shift-enter when
you're done.)


*Write your answer here, replacing this text.*


## Errors in Naming


**Question 1.** When you run the following cell, Python will produce a
slightly cryptic error message.  Explain in the text cell below, in your own
words, what's wrong with the code.

```{python}
4 = 2 + 2
```

*Write your answer here, replacing this text.*


**Question 2**. When you run the following cell, Python will produce another
slightly cryptic error message. Fix the error, and then explain below in your
own words what was wrong with the code.

```{python}
two = 2
four = two plus two
```

*Write your answer here, replacing this text.*
