---
jupyter:
  jupytext:
    formats: Rmd:rmarkdown,ipynb
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.2
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.6.5
---

```{python}
# HIDDEN
# The standard set of libraries we need
import numpy as np
```

# A simpler problem

Imagine a family with four children.

What is the probability that the family will have exactly three girls?

There are various ways to answer this question.  One way, is to use
*simulation*.

Simulation makes a *model* of the problem.  We use the model to generate
*simulated* data.  If the model is a good one, the simulated data should look
like the real data.

First we need to simulate a family of four children.

Then we need to count the number of girls.

We do this many many times, and see how often we get a count of 3.

For example, we can run the following cell 4 times, to get 4 random numbers.
We can chose to consider any random number less than or equal to 0.5 to be a
girl.  If we count how many random numbers (of 4) are less then or equal to
0.5, we

```{python}
np.random.uniform()
```

As we will soon see, we are using a *call expression* here.  `np.random.uniform()` *calls* the function, and returns a random number, between 0 and 1.


It's inconvenient to have to run this cell many times.   We really need some
machinery to make the computer do that for us.  We need *expressions*,
*names*, *call expressions*, *comparisons* and *arrays*.  We will deal with
those next.
