---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 0.8.7
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
# HIDDEN

# The standard set of libraries we need
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

# Make plots look a little bit more fancy
plt.style.use('fivethirtyeight')
```

### Conditional Statements ###

In many situations, actions and results depends on a specific set of
conditions being satisfied. For example, individuals in randomized
controlled trials receive the treatment if they have been assigned to
the treatment group. A gambler makes money if she wins her bet.

In this section we will learn how to describe such situations using
code. A *conditional statement* is a multi-line statement that allows
Python to choose among different alternatives based on the truth value
of an expression.

A conditional statement always begins with an `if` header, which is
a single line followed by an indented body. The body is only executed
if the expression directly following `if` (called the *if expression*)
evaluates to a true value. If the *if expression* evaluates to a false
value, then the body of the `if` is skipped.

Soon we will make a cell that prints "Positive" if the variable `x`
refers to a positive number.

First we set `x` to something.

```{python}
# Set x
x = 1
```

Here's a comparison *expression*:

```{python}
# True if x is positive
x > 0
```

We use the expression as an *if expression*:


```{python}
# Our first conditional statement
if x > 0:
    print('Positive')
```

This cell prints "Positive" if `x` is a positive number. But if `x` is
not a positive number, then the *if expression* evaluates to a false
value, and so Python skips the `print` statement.

```{python}
x = 0
```

```{python}
# Nothing printed this time
if x > 0:
    print('Positive')
```

Notice the indentation of the `print` line.  The indentation tells
Python which lines are in the *body* of the *if statement*.  Python
only runs the indented lines if the *if expression* is a true value.

To show that, let's print two things, when the number is positive.

```{python}
# Still nothing printed
if x > 0:
    print('Positive')
    print('Positively spiffing')
```

Now when `x` is positive.

```{python}
x = 1
```

```{python}
# Both lines printed this time.
if x > 0:
    print('Positive')
    print('Positively spiffing')
```

Let us refine our cell to print `Negative` if `x` is a negative
number. We can do this by adding an `elif` clause, where `elif` if
Python's shorthand for the phrase "else if".

```{python}
if x > 0:
    print('Positive')
elif x < 0:
    print('Negative')
```

Now the cell gives the correct answer when the input is -3:

```{python}
x = -3
```

```{python}
if x > 0:
    print('Positive')
elif x < 0:
    print('Negative')
```

What if `x` is 0?


```{python}
x = 0
```

To deal with this case, we can add another `elif` clause:

```{python}
if x > 0:
    print('Positive')
elif x < 0:
    print('Negative')
elif x == 0:
    print('Neither positive nor negative')
```

Equivalently, we can replaced the final `elif` clause by an `else` clause, whose body will be executed only if all the previous comparisons are false; that is, if the input value is equal to 0.

```{python}
if x > 0:
    print('Positive')
elif x < 0:
    print('Negative')
else:
    print('Neither positive nor negative')
```

### The General Form ###

A conditional statement can also have multiple clauses with multiple
bodies, and only one of those bodies can ever be executed. The general
format of a multi-clause conditional statement appears below.

    if <if expression>:
        <if body>
    elif <elif expression 0>:
        <elif body 0>
    elif <elif expression 1>:
        <elif body 1>
    ...
    else:
        <else body>

There is always exactly one `if` clause, but there can be any number of
`elif` clauses. Python will evaluate the `if` and `elif` expressions in
the headers in order until one is found that is a true value, then
execute the corresponding body. The `else` clause is optional. When an
`else` header is provided, its *else body* is executed only if none of
the header expressions of the previous clauses are true. The `else`
clause must always come at the end (or not at all).

{% data8page Conditional_Statements %}
